server.port=8000
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/waterflex}
spring.datasource.username=${DATABASE_USER:waterflex}
spring.datasource.password=${DATABASE_PASSWORD:waterflex}
spring.datasource.hikari.maximum-pool-size=10
routing.url=${ROUTING_URL:http://localhost:8001}
